// src/components/vuetify/SplatFastNavShowcase.vue
<script lang="ts">
import { DEFAULT_FAST_NAV_RECOVERY, type FastNavRecoveryConfig, type StrayTrimOptions, type PruneFloatersOptions } from '@/navigation/fastNav';

/** A selectable example splat scene shown in the "Example scenes" menu. */
export interface ExampleScene {
  readonly title: string;
  readonly url: string;
}

/** Built-in example scenes; override via the `exampleScenes` prop. */
export const DEFAULT_EXAMPLE_SCENES: readonly ExampleScene[] = [
  { title: 'Bedroom', url: 'https://raw.githubusercontent.com/EricEisaman/assets/main/environment/splats/bedroom.ply' },
  { title: 'Tropical Compound', url: 'https://raw.githubusercontent.com/EricEisaman/assets/main/environment/splats/tropical_compound.ply' },
  { title: 'Industrial Warehouse', url: 'https://raw.githubusercontent.com/EricEisaman/assets/main/environment/splats/industrial_warehouse.ply' },
  { title: 'Stairs', url: 'https://raw.githubusercontent.com/EricEisaman/assets/main/environment/splats/stairs.spz' },
];

// Re-exported so integrators can extend the built-in recovery ladder.
export { DEFAULT_FAST_NAV_RECOVERY };
export type { FastNavRecoveryConfig, StrayTrimOptions, PruneFloatersOptions };
</script>

<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, reactive, ref, watch, type ComponentPublicInstance } from 'vue';

import { useBabylonViewer } from '@/composables/useBabylonViewer';
import { useSplatFastNav, type LogTag, type SogExportMode } from '@/composables/useSplatFastNav';
import {
  clampSliceSettingsForScene,
  DEFAULT_AUTO_SLICE_THRESHOLD,
  DEFAULT_SLICE_SETTINGS,
  type SliceSettings,
} from '@/wasm/sogTypes';

const props = withDefaults(
  defineProps<{
    /** Override/extend the built-in adaptive FAST NAV recovery ladder. */
    recovery?: Partial<FastNavRecoveryConfig>;
    /** Override stray-floater trimming of the detected floor (on by default). */
    strayTrim?: StrayTrimOptions;
    /** Override WASM-side floater pruning / statistical outlier removal (on by default). */
    prune?: PruneFloatersOptions;
    /** Override the example scenes shown in the "Example scenes" menu. */
    exampleScenes?: readonly ExampleScene[];
    /** Override the default SOG export / streamed-slice settings. */
    slice?: SliceSettings;
    /**
     * Splat count above which streamed (LOD) export is recommended by default.
     * Defaults to {@link DEFAULT_AUTO_SLICE_THRESHOLD} (1,000,000).
     */
    autoSliceThreshold?: number;
  }>(),
  {
    // Empty object resolves to DEFAULT_FAST_NAV_RECOVERY inside the pipeline,
    // so adaptive recovery is built-in even when no prop is supplied.
    recovery: () => ({}),
    strayTrim: undefined,
    prune: undefined,
    exampleScenes: () => DEFAULT_EXAMPLE_SCENES,
    slice: () => ({}),
    autoSliceThreshold: DEFAULT_AUTO_SLICE_THRESHOLD,
  }
);

const canvasRef = ref<HTMLCanvasElement | null>(null);
const fileInputRef = ref<HTMLInputElement | null>(null);
const cardRef = ref<ComponentPublicInstance | null>(null);
const isDragging = ref(false);
const isFullscreen = ref(false);

// Babylon is left-handed by default - the one correct setting for everyday use.
// A right-handed scene (scene.useRightHandedSystem, the PR #18606 counterpart) is
// a conformance/regression path only, so it is gated behind a hidden `?rh=1` URL
// flag (the handedness regression scene) rather than a user-facing toggle.
const rightHanded = new URLSearchParams(window.location.search).get('rh') === '1';

const babylon = useBabylonViewer(canvasRef, { rightHanded });
const { status, statusMessage, errorMessage, logs, isBusy, phase, progress, splatCount, maxShDegree, maxChunkExtent, loadAndProcess, loadExample, exportSog, exportNavmesh, generateCollisionBoundary, exportCollisionMesh, setCollisionBoundaryVisible, setNavMeshVisible, reset } =
  useSplatFastNav(babylon, { recovery: props.recovery, strayTrim: props.strayTrim, prune: props.prune });

// --- Streamed SOG export -------------------------------------------------
// Reactive slice settings seeded from the defaults + any `slice` prop override.
const sliceForm = reactive({
  sh_degree: props.slice.sh_degree ?? DEFAULT_SLICE_SETTINGS.sh_degree,
  sh_cluster_count: props.slice.sh_cluster_count ?? DEFAULT_SLICE_SETTINGS.sh_cluster_count,
  sh_iterations: props.slice.sh_iterations ?? DEFAULT_SLICE_SETTINGS.sh_iterations,
  chunk_count: props.slice.chunk_count ?? DEFAULT_SLICE_SETTINGS.chunk_count,
  chunk_extent: props.slice.chunk_extent ?? DEFAULT_SLICE_SETTINGS.chunk_extent,
  lod_levels: props.slice.lod_levels ?? DEFAULT_SLICE_SETTINGS.lod_levels,
});

const isLargeScene = computed(
  () => splatCount.value !== null && splatCount.value > props.autoSliceThreshold
);
// Default to streamed export for large scenes (>1M splats), single otherwise.
const sogMode = ref<SogExportMode>('streamed');
const sogExporting = ref(false);
const sogSummary = ref<string | null>(null);
const collisionBoundaryVisible = ref(true);
const collisionExporting = ref(false);
const navMeshVisible = ref(true);
const collisionSummary = ref<string | null>(null);
const navExporting = ref(false);
const navSummary = ref<string | null>(null);

// Auto-pick the recommended mode whenever a new scene's count resolves; the
// user can still flip it before exporting.
watch(splatCount, () => {
  collisionSummary.value = null;
  navSummary.value = null;
  sogSummary.value = null;
  navMeshVisible.value = true;
  sogMode.value = isLargeScene.value ? 'streamed' : 'single';
});

watch([maxShDegree, maxChunkExtent], () => {
  sliceForm.sh_degree = Math.min(sliceForm.sh_degree, maxShDegree.value);
  sliceForm.chunk_extent = Math.min(sliceForm.chunk_extent, maxChunkExtent.value);
});

const sogStatusText = computed(() => {
  if (sogSummary.value) return sogSummary.value;
  if (splatCount.value === null) return null;
  return isLargeScene.value
    ? `${splatCount.value.toLocaleString()} splats — large scene. Streamed LOD export recommended.`
    : `${splatCount.value.toLocaleString()} splats. Streamed or single SOG export available.`;
});

const showLodLevelsWarning = computed(
  () => sogMode.value === 'streamed' && sliceForm.lod_levels === 1,
);

const sogExportButtonLabel = computed(() =>
  sogMode.value === 'streamed' ? 'Export streamed SOG (.zip)' : 'Export single SOG (.zip)',
);

async function runSogExport(): Promise<void> {
  if (sogExporting.value) return;
  sogExporting.value = true;
  sogSummary.value = null;
  try {
    const archive = await exportSog(
      sogMode.value,
      clampSliceSettingsForScene(sliceForm, {
        maxShDegree: maxShDegree.value,
        maxChunkExtent: maxChunkExtent.value,
      })
    );
    const mb = (archive.byteLength / 1e6).toFixed(1);
    sogSummary.value = `Exported ${archive.chunkCount} chunk(s), ${archive.fileCount} files (${mb} MB).`;
  } catch (error) {
    sogSummary.value = `Export failed: ${error instanceof Error ? error.message : String(error)}`;
  } finally {
    sogExporting.value = false;
  }
}

async function runCollisionGenerate(): Promise<void> {
  if (collisionExporting.value) return;
  collisionExporting.value = true;
  collisionSummary.value = null;
  try {
    const artifact = await generateCollisionBoundary();
    collisionBoundaryVisible.value = true;
    collisionSummary.value = `Collision boundary: ${artifact.result.mesh.vertex_count} vertices, ${artifact.result.mesh.face_count} faces.`;
  } catch (error) {
    collisionSummary.value = `Collision generation failed: ${error instanceof Error ? error.message : String(error)}`;
  } finally {
    collisionExporting.value = false;
  }
}

async function runCollisionExport(): Promise<void> {
  if (collisionExporting.value) return;
  collisionExporting.value = true;
  try {
    const bytes = await exportCollisionMesh();
    collisionSummary.value = `Exported collision mesh (${(bytes.byteLength / 1e6).toFixed(1)} MB).`;
  } catch (error) {
    collisionSummary.value = `Collision export failed: ${error instanceof Error ? error.message : String(error)}`;
  } finally {
    collisionExporting.value = false;
  }
}

async function runNavmeshExport(): Promise<void> {
  if (navExporting.value) return;
  navExporting.value = true;
  try {
    await exportNavmesh();
    navSummary.value = 'Navmesh export started.';
  } catch (error) {
    navSummary.value = `Navmesh export failed: ${error instanceof Error ? error.message : String(error)}`;
  } finally {
    navExporting.value = false;
  }
}

function onNavMeshVisible(visible: boolean): void {
  navMeshVisible.value = visible;
  setNavMeshVisible(visible);
}

// Human-readable progress suffix (e.g. "Pruning floaters 42%") when the worker
// reports a real fraction during the prune pass.
const progressText = computed(() => {
  const p = progress.value;
  if (!p) return null;
  const labels: Record<string, string> = {
    parse: 'Parsing splat',
    prune: 'Pruning floaters',
    field: 'Building floor field',
  };
  const base = labels[p.stage] ?? 'Processing';
  return p.fraction !== null ? `${base} ${Math.round(p.fraction * 100)}%` : base;
});

const showSnackbar = computed({
  get: () => errorMessage.value !== null,
  set: (value: boolean) => {
    if (!value) {
      errorMessage.value = null;
    }
  },
});

const showDropZone = computed(() => status.value === 'idle' || status.value === 'error');

const steps = computed(() => {
  const loadDone = status.value === 'processing' || status.value === 'done';
  const navDone = status.value === 'done';
  const p = phase.value;
  const pruneActive = status.value === 'processing' && p === 'prune';
  const pruneDone = p === 'floor' || p === 'navmesh' || p === 'done';
  const navActive = status.value === 'processing' && (p === 'floor' || p === 'navmesh');
  const pruneLabel = pruneActive && progressText.value ? progressText.value : 'Prune outliers';
  return [
    { label: 'Load splat', active: status.value === 'loading', done: loadDone },
    { label: pruneLabel, active: pruneActive, done: pruneDone || navDone },
    { label: 'FAST NAV', active: navActive, done: navDone },
    { label: 'Top-down view', active: false, done: navDone },
  ];
});

const tagColor: Record<LogTag, string> = {
  info: 'info',
  wait: 'warning',
  warn: 'warning',
  error: 'error',
  success: 'success',
  worker: 'accent',
};

function pickFile(file: File | null | undefined): void {
  if (file) {
    void loadAndProcess(file);
  }
}

function onBrowse(): void {
  fileInputRef.value?.click();
}

function onFileChange(event: Event): void {
  const input = event.target as HTMLInputElement;
  pickFile(input.files?.[0]);
  input.value = '';
}

function onDrop(event: DragEvent): void {
  isDragging.value = false;
  pickFile(event.dataTransfer?.files?.[0]);
}

async function toggleFullscreen(): Promise<void> {
  const el = cardRef.value?.$el as HTMLElement | undefined;
  if (!el) {
    return;
  }
  if (document.fullscreenElement) {
    await document.exitFullscreen();
  } else {
    await el.requestFullscreen();
  }
}

function onFullscreenChange(): void {
  isFullscreen.value = document.fullscreenElement !== null;
  // Let the browser settle the new layout before resizing the Babylon engine.
  window.setTimeout(() => babylon.viewer.value?.resize(), 60);
}

onMounted(() => document.addEventListener('fullscreenchange', onFullscreenChange));
onBeforeUnmount(() => document.removeEventListener('fullscreenchange', onFullscreenChange));
</script>

<template>
  <v-container fluid class="pa-4">
    <v-row justify="center">
      <v-col cols="12" md="10" lg="9">
        <div class="text-h5 font-weight-black text-uppercase mb-1">
          Gaussian Splat <span class="text-primary">FAST NAV</span>
        </div>
        <p class="text-body-2 text-medium-emphasis mb-4">
          Drop a <strong>.ply</strong>, <strong>.spz</strong>, or <strong>.splat</strong> 3D Gaussian Splat. It loads into Babylon.js, auto-runs
          the FAST NAV pipeline (collider &rarr; navmesh &rarr; crowd &rarr; NPC), then frames the player top-down.
        </p>

        <div class="d-flex flex-wrap ga-2 mb-4">
          <v-chip
            v-for="step in steps"
            :key="step.label"
            :color="step.done ? 'success' : step.active ? 'primary' : undefined"
            :variant="step.done || step.active ? 'flat' : 'outlined'"
            size="small"
          >
            <v-icon start :icon="step.done ? 'mdi-check-circle' : step.active ? 'mdi-loading mdi-spin' : 'mdi-circle-outline'" />
            {{ step.label }}
          </v-chip>
        </div>

        <v-card
          ref="cardRef"
          border
          color="surface"
          class="position-relative overflow-hidden canvas-card"
          :class="{ 'drop-active': isDragging }"
          @dragenter.prevent="isDragging = true"
          @dragover.prevent="isDragging = true"
          @dragleave.prevent="isDragging = false"
          @drop.prevent="onDrop"
        >
          <canvas ref="canvasRef" class="showcase-canvas" />

          <v-btn
            v-if="status === 'done'"
            class="fullscreen-btn"
            :icon="isFullscreen ? 'mdi-fullscreen-exit' : 'mdi-fullscreen'"
            :title="isFullscreen ? 'Exit fullscreen' : 'Fullscreen'"
            color="primary"
            variant="flat"
            size="small"
            @click="toggleFullscreen"
          />

          <v-overlay
            :model-value="showDropZone"
            contained
            persistent
            scrim="rgba(5, 5, 5, 0.82)"
            class="align-center justify-center"
          >
            <div class="text-center pa-8">
              <v-icon icon="mdi-cloud-upload-outline" size="72" color="primary" class="mb-3" />
              <div class="text-h6 font-weight-bold mb-2">Drop your splat here</div>
              <div class="text-body-2 text-medium-emphasis mb-5">.ply, .spz, or .splat · drag &amp; drop, browse, or pick an example</div>
              <div class="d-flex flex-wrap justify-center align-center ga-3">
                <v-btn color="primary" size="large" prepend-icon="mdi-folder-open" @click="onBrowse">
                  Browse files
                </v-btn>
                <v-menu>
                  <template #activator="{ props: menuProps }">
                    <v-btn
                      v-bind="menuProps"
                      color="secondary"
                      size="large"
                      prepend-icon="mdi-cube-scan"
                      append-icon="mdi-menu-down"
                    >
                      Example scenes
                    </v-btn>
                  </template>
                  <v-list>
                    <v-list-item
                      v-for="scene in props.exampleScenes"
                      :key="scene.url"
                      :title="scene.title"
                      prepend-icon="mdi-cube-outline"
                      @click="loadExample(scene.url, scene.title)"
                    />
                  </v-list>
                </v-menu>
              </div>
            </div>
          </v-overlay>

          <v-overlay
            :model-value="isBusy"
            contained
            persistent
            scrim="rgba(5, 5, 5, 0.6)"
            class="align-center justify-center"
          >
            <div class="text-center">
              <v-progress-circular
                :indeterminate="!progress || progress.fraction === null"
                :model-value="progress && progress.fraction !== null ? progress.fraction * 100 : undefined"
                color="primary"
                size="64"
                width="5"
                class="mb-3"
              />
              <div class="text-body-1">{{ statusMessage }}</div>
              <div v-if="progressText" class="text-caption text-medium-emphasis mt-1">{{ progressText }}</div>
            </div>
          </v-overlay>
        </v-card>

        <div class="d-flex align-center justify-space-between flex-wrap ga-2 mt-3">
          <div class="text-body-2 text-medium-emphasis">{{ statusMessage }}</div>
          <v-btn
            v-if="status === 'done' || status === 'error'"
            variant="text"
            color="secondary"
            prepend-icon="mdi-refresh"
            @click="reset"
          >
            Load another
          </v-btn>
        </div>

        <v-expansion-panels v-if="status === 'done'" class="mt-4" variant="accordion">
          <v-expansion-panel title="Navigation and collision exports">
            <template #text>
              <div v-if="navSummary" class="text-caption text-medium-emphasis mb-3">{{ navSummary }}</div>
              <div class="d-flex flex-wrap ga-3 mb-4">
                <v-btn
                  color="primary"
                  :loading="navExporting"
                  prepend-icon="mdi-download"
                  @click="runNavmeshExport"
                >
                  Export navmesh (.nav)
                </v-btn>
              </div>

              <v-sheet
                border
                rounded="lg"
                class="d-flex align-center flex-wrap ga-4 pa-3 mb-4 navmesh-toggle-bar"
                color="surface"
              >
                <v-icon
                  :icon="navMeshVisible ? 'mdi-layers' : 'mdi-layers-off'"
                  :color="navMeshVisible ? 'success' : 'medium-emphasis'"
                  size="22"
                />
                <div class="flex-grow-1">
                  <div class="text-body-2 font-weight-medium">Navmesh overlay</div>
                  <div class="text-caption text-medium-emphasis">
                    {{
                      navMeshVisible
                        ? 'Green walkable mesh visible — click it to move the player'
                        : 'Hidden — splat view only; click-to-move is off'
                    }}
                  </div>
                </div>
                <v-switch
                  :model-value="navMeshVisible"
                  color="success"
                  density="comfortable"
                  hide-details
                  inset
                  :disabled="isBusy"
                  :label="navMeshVisible ? 'Shown' : 'Hidden'"
                  @update:model-value="onNavMeshVisible(Boolean($event))"
                />
              </v-sheet>

              <v-divider class="mb-4" />

              <div v-if="collisionSummary" class="text-caption text-medium-emphasis mb-3">{{ collisionSummary }}</div>
              <div class="d-flex flex-wrap align-center ga-3">
                <v-btn
                  color="secondary"
                  :loading="collisionExporting"
                  prepend-icon="mdi-cube-outline"
                  @click="runCollisionGenerate"
                >
                  Generate collision boundary
                </v-btn>
                <v-switch
                  v-model="collisionBoundaryVisible"
                  color="primary"
                  density="compact"
                  hide-details
                  label="Show collision boundary"
                  @update:model-value="setCollisionBoundaryVisible(Boolean($event))"
                />
                <v-btn
                  variant="tonal"
                  :loading="collisionExporting"
                  prepend-icon="mdi-download"
                  @click="runCollisionExport"
                >
                  Export collision mesh (.glb)
                </v-btn>
              </div>
            </template>
          </v-expansion-panel>

          <v-expansion-panel title="Streamed SOG export">
            <template #text>
              <div v-if="sogStatusText" class="text-caption mb-3" :class="isLargeScene ? 'text-primary' : 'text-medium-emphasis'">
                {{ sogStatusText }}
              </div>

              <v-btn-toggle v-model="sogMode" mandatory density="comfortable" color="primary" class="mb-4">
                <v-btn value="streamed" prepend-icon="mdi-layers-triple">Streamed LOD</v-btn>
                <v-btn value="single" prepend-icon="mdi-file-outline">Single SOG</v-btn>
              </v-btn-toggle>

              <v-row dense>
                <v-col cols="12" sm="4">
                  <v-text-field
                    v-model.number="sliceForm.sh_degree"
                    type="number" min="0" :max="maxShDegree" step="1"
                    label="SH Degree" density="compact" variant="outlined"
                    hint="0 = base color only (smaller/faster). Higher degrees keep more view-dependent color."
                    persistent-hint
                  />
                </v-col>
                <v-col cols="12" sm="4">
                  <v-text-field
                    v-model.number="sliceForm.sh_cluster_count"
                    type="number" min="1" max="65536" step="256"
                    label="SH Palette Size" density="compact" variant="outlined" hide-details
                  />
                </v-col>
                <v-col cols="12" sm="4">
                  <v-text-field
                    v-model.number="sliceForm.sh_iterations"
                    type="number" min="1" max="50" step="1"
                    label="SH Iterations" density="compact" variant="outlined" hide-details
                  />
                </v-col>
                <template v-if="sogMode === 'streamed'">
                  <v-col cols="12" sm="4">
                    <v-text-field
                      v-model.number="sliceForm.chunk_count"
                      type="number" min="1000" max="4000000" step="16000"
                      label="Splats / Chunk" density="compact" variant="outlined" hide-details
                    />
                  </v-col>
                  <v-col cols="12" sm="4">
                    <v-text-field
                      v-model.number="sliceForm.chunk_extent"
                      type="number" min="0" :max="maxChunkExtent" step="1"
                      label="Chunk Extent (m)" density="compact" variant="outlined" hide-details
                    />
                  </v-col>
                  <v-col cols="12" sm="4">
                    <v-text-field
                      v-model.number="sliceForm.lod_levels"
                      type="number" min="1" max="6" step="1"
                      label="LOD Levels" density="compact" variant="outlined"
                      hint="2+ recommended for streaming (coarse base + full detail). 1 = full detail only, no multi-LOD."
                      persistent-hint
                    />
                  </v-col>
                </template>
              </v-row>

              <v-alert
                v-if="showLodLevelsWarning"
                class="mt-3"
                type="warning"
                density="compact"
                variant="tonal"
              >
                LOD Levels is 1 — this export is a single detail level and will not stream coarse→fine.
              </v-alert>

              <v-btn
                class="mt-4"
                color="primary"
                :loading="sogExporting"
                prepend-icon="mdi-download"
                @click="runSogExport"
              >
                {{ sogExportButtonLabel }}
              </v-btn>
            </template>
          </v-expansion-panel>
        </v-expansion-panels>

        <v-expansion-panels v-if="logs.length" class="mt-4" variant="accordion">
          <v-expansion-panel title="System logs">
            <template #text>
              <div class="logs-scroll font-monospace text-caption">
                <div v-for="entry in logs" :key="entry.id" class="py-1">
                  <v-chip :color="tagColor[entry.tag]" size="x-small" label class="mr-2 text-uppercase">
                    {{ entry.tag }}
                  </v-chip>
                  <span>{{ entry.message }}</span>
                </div>
              </div>
            </template>
          </v-expansion-panel>
        </v-expansion-panels>
      </v-col>
    </v-row>

    <input
      ref="fileInputRef"
      type="file"
      accept=".ply,.spz,.splat"
      class="d-none"
      @change="onFileChange"
    >

    <v-snackbar v-model="showSnackbar" color="error" :timeout="6000" location="bottom">
      {{ errorMessage }}
      <template #actions>
        <v-btn variant="text" @click="showSnackbar = false">Close</v-btn>
      </template>
    </v-snackbar>
  </v-container>
</template>

<style scoped>
.showcase-canvas {
  display: block;
  width: 100%;
  height: clamp(360px, 68vh, 760px);
  background-color: #000;
  outline: none;
  touch-action: none;
}

.drop-active {
  outline: 2px dashed rgb(var(--v-theme-primary));
  outline-offset: -6px;
}

.fullscreen-btn {
  position: absolute;
  top: 12px;
  right: 12px;
  z-index: 5;
}

.canvas-card:fullscreen {
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: #000;
}

.canvas-card:fullscreen .showcase-canvas {
  width: 100vw;
  height: 100vh;
}

.logs-scroll {
  max-height: 240px;
  overflow-y: auto;
}

.navmesh-toggle-bar {
  background: linear-gradient(
    120deg,
    rgba(var(--v-theme-success), 0.08),
    rgba(var(--v-theme-surface), 1) 42%
  );
}
</style>

// src/react/SplatFastNavShowcase.tsx
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import Accordion from '@mui/material/Accordion';
import AccordionDetails from '@mui/material/AccordionDetails';
import AccordionSummary from '@mui/material/AccordionSummary';
import Alert from '@mui/material/Alert';
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';
import Chip from '@mui/material/Chip';
import CircularProgress from '@mui/material/CircularProgress';
import Container from '@mui/material/Container';
import FormControlLabel from '@mui/material/FormControlLabel';
import Grid from '@mui/material/Grid';
import IconButton from '@mui/material/IconButton';
import Menu from '@mui/material/Menu';
import MenuItem from '@mui/material/MenuItem';
import Paper from '@mui/material/Paper';
import Snackbar from '@mui/material/Snackbar';
import Switch from '@mui/material/Switch';
import TextField from '@mui/material/TextField';
import ToggleButton from '@mui/material/ToggleButton';
import ToggleButtonGroup from '@mui/material/ToggleButtonGroup';
import Typography from '@mui/material/Typography';
import ArrowDropDownIcon from '@mui/icons-material/ArrowDropDown';
import AutorenewIcon from '@mui/icons-material/Autorenew';
import CheckCircleIcon from '@mui/icons-material/CheckCircle';
import CloudUploadIcon from '@mui/icons-material/CloudUpload';
import DownloadIcon from '@mui/icons-material/Download';
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';
import FolderOpenIcon from '@mui/icons-material/FolderOpen';
import FullscreenIcon from '@mui/icons-material/Fullscreen';
import FullscreenExitIcon from '@mui/icons-material/FullscreenExit';
import LayersIcon from '@mui/icons-material/Layers';
import LayersClearIcon from '@mui/icons-material/LayersClear';
import RadioButtonUncheckedIcon from '@mui/icons-material/RadioButtonUnchecked';
import RefreshIcon from '@mui/icons-material/Refresh';
import ViewInArIcon from '@mui/icons-material/ViewInAr';

import { SceneCanvas } from '@/react/SceneCanvas';
import { DEFAULT_EXAMPLE_SCENES } from '@/react/exampleScenes';
import { useSplatFastNavR3F, type LogTag, type SogExportMode } from '@/react/useSplatFastNavR3F';
import {
  clampSliceSettingsForScene,
  DEFAULT_AUTO_SLICE_THRESHOLD,
  DEFAULT_SLICE_SETTINGS,
} from '@/wasm/sogTypes';

const tagColor: Record<LogTag, 'info' | 'warning' | 'error' | 'success' | 'secondary'> = {
  info: 'info',
  wait: 'warning',
  warn: 'warning',
  error: 'error',
  success: 'success',
  worker: 'secondary',
};

export function SplatFastNavShowcase(): JSX.Element {
  const nav = useSplatFastNavR3F();
  const {
    controller,
    status,
    statusMessage,
    errorMessage,
    setErrorMessage,
    logs,
    isBusy,
    phase,
    progress,
    splatCount,
    maxShDegree,
    maxChunkExtent,
    loadAndProcess,
    loadExample,
    exportNavmesh,
    generateCollisionBoundary,
    exportCollisionMesh,
    setCollisionBoundaryVisible,
    setNavMeshVisible,
    exportSog,
    reset,
  } = nav;

  const fileInputRef = useRef<HTMLInputElement | null>(null);
  const cardRef = useRef<HTMLDivElement | null>(null);
  const [isDragging, setIsDragging] = useState(false);
  const [isFullscreen, setIsFullscreen] = useState(false);
  const [exampleAnchor, setExampleAnchor] = useState<null | HTMLElement>(null);

  const [sliceForm, setSliceForm] = useState({
    sh_degree: DEFAULT_SLICE_SETTINGS.sh_degree,
    sh_cluster_count: DEFAULT_SLICE_SETTINGS.sh_cluster_count,
    sh_iterations: DEFAULT_SLICE_SETTINGS.sh_iterations,
    chunk_count: DEFAULT_SLICE_SETTINGS.chunk_count,
    chunk_extent: DEFAULT_SLICE_SETTINGS.chunk_extent,
    lod_levels: DEFAULT_SLICE_SETTINGS.lod_levels,
  });
  const isLargeScene = splatCount !== null && splatCount > DEFAULT_AUTO_SLICE_THRESHOLD;
  const [sogMode, setSogMode] = useState<SogExportMode>('streamed');
  const [sogExporting, setSogExporting] = useState(false);
  const [sogSummary, setSogSummary] = useState<string | null>(null);
  const [collisionBoundaryVisible, setCollisionBoundaryVisibleState] = useState(true);
  const [collisionExporting, setCollisionExporting] = useState(false);
  const [collisionSummary, setCollisionSummary] = useState<string | null>(null);
  const [navMeshVisible, setNavMeshVisibleState] = useState(true);
  const [navExporting, setNavExporting] = useState(false);
  const [navSummary, setNavSummary] = useState<string | null>(null);

  useEffect(() => {
    setCollisionSummary(null);
    setNavSummary(null);
    setSogSummary(null);
    setNavMeshVisibleState(true);
    setSogMode(isLargeScene ? 'streamed' : 'single');
  }, [splatCount, isLargeScene]);

  useEffect(() => {
    setSliceForm((prev) => ({
      ...prev,
      sh_degree: Math.min(prev.sh_degree, maxShDegree),
      chunk_extent: Math.min(prev.chunk_extent, maxChunkExtent),
    }));
  }, [maxChunkExtent, maxShDegree]);

  const progressText = useMemo(() => {
    if (!progress) return null;
    const labels: Record<string, string> = {
      parse: 'Parsing splat',
      prune: 'Pruning floaters',
      field: 'Building floor field',
    };
    const baseLabel = labels[progress.stage] ?? 'Processing';
    return progress.fraction !== null ? `${baseLabel} ${Math.round(progress.fraction * 100)}%` : baseLabel;
  }, [progress]);

  const steps = useMemo(() => {
    const loadDone = status === 'processing' || status === 'done';
    const navDone = status === 'done';
    const pruneActive = status === 'processing' && phase === 'prune';
    const pruneDone = phase === 'floor' || phase === 'navmesh' || phase === 'done';
    const navActive = status === 'processing' && (phase === 'floor' || phase === 'navmesh');
    const pruneLabel = pruneActive && progressText ? progressText : 'Prune outliers';
    return [
      { label: 'Load splat', active: status === 'loading', done: loadDone },
      { label: pruneLabel, active: pruneActive, done: pruneDone || navDone },
      { label: 'FAST NAV', active: navActive, done: navDone },
      { label: 'Top-down view', active: false, done: navDone },
    ];
  }, [status, phase, progressText]);

  const sogStatusText = useMemo(() => {
    if (sogSummary) return sogSummary;
    if (splatCount === null) return null;
    return isLargeScene
      ? `${splatCount.toLocaleString()} splats - large scene. Streamed LOD export recommended.`
      : `${splatCount.toLocaleString()} splats. Streamed or single SOG export available.`;
  }, [sogSummary, splatCount, isLargeScene]);

  const showLodLevelsWarning = sogMode === 'streamed' && sliceForm.lod_levels === 1;
  const sogExportButtonLabel =
    sogMode === 'streamed' ? 'Export streamed SOG (.zip)' : 'Export single SOG (.zip)';

  const showDropZone = status === 'idle' || status === 'error';

  const pickFile = useCallback(
    (file: File | null | undefined): void => {
      if (file) void loadAndProcess(file);
    },
    [loadAndProcess]
  );

  const onFileChange = (event: React.ChangeEvent<HTMLInputElement>): void => {
    pickFile(event.target.files?.[0]);
    event.target.value = '';
  };

  const onDrop = (event: React.DragEvent<HTMLDivElement>): void => {
    event.preventDefault();
    setIsDragging(false);
    pickFile(event.dataTransfer?.files?.[0]);
  };

  const toggleFullscreen = useCallback(async (): Promise<void> => {
    const el = cardRef.current;
    if (!el) return;
    if (document.fullscreenElement) await document.exitFullscreen();
    else await el.requestFullscreen();
  }, []);

  useEffect(() => {
    const onChange = (): void => setIsFullscreen(document.fullscreenElement !== null);
    document.addEventListener('fullscreenchange', onChange);
    return () => document.removeEventListener('fullscreenchange', onChange);
  }, []);

  const runSogExport = useCallback(async (): Promise<void> => {
    if (sogExporting) return;
    setSogExporting(true);
    setSogSummary(null);
    try {
      const archive = await exportSog(
        sogMode,
        clampSliceSettingsForScene(sliceForm, { maxShDegree, maxChunkExtent })
      );
      const mb = (archive.byteLength / 1e6).toFixed(1);
      setSogSummary(`Exported ${archive.chunkCount} chunk(s), ${archive.fileCount} files (${mb} MB).`);
    } catch (error) {
      setSogSummary(`Export failed: ${error instanceof Error ? error.message : String(error)}`);
    } finally {
      setSogExporting(false);
    }
  }, [exportSog, maxChunkExtent, maxShDegree, sliceForm, sogExporting, sogMode]);

  const runCollisionGenerate = useCallback(async (): Promise<void> => {
    if (collisionExporting) return;
    setCollisionExporting(true);
    setCollisionSummary(null);
    try {
      const artifact = await generateCollisionBoundary();
      setCollisionBoundaryVisibleState(true);
      setCollisionSummary(
        `Collision boundary: ${artifact.result.mesh.vertex_count} vertices, ${artifact.result.mesh.face_count} faces.`
      );
    } catch (error) {
      setCollisionSummary(`Collision generation failed: ${error instanceof Error ? error.message : String(error)}`);
    } finally {
      setCollisionExporting(false);
    }
  }, [collisionExporting, generateCollisionBoundary]);

  const runCollisionExport = useCallback(async (): Promise<void> => {
    if (collisionExporting) return;
    setCollisionExporting(true);
    try {
      const bytes = await exportCollisionMesh();
      setCollisionSummary(`Exported collision mesh (${(bytes.byteLength / 1e6).toFixed(1)} MB).`);
    } catch (error) {
      setCollisionSummary(`Collision export failed: ${error instanceof Error ? error.message : String(error)}`);
    } finally {
      setCollisionExporting(false);
    }
  }, [collisionExporting, exportCollisionMesh]);

  const runNavmeshExport = useCallback(async (): Promise<void> => {
    if (navExporting) return;
    setNavExporting(true);
    try {
      await exportNavmesh();
      setNavSummary('Navmesh export started.');
    } catch (error) {
      setNavSummary(`Navmesh export failed: ${error instanceof Error ? error.message : String(error)}`);
    } finally {
      setNavExporting(false);
    }
  }, [exportNavmesh, navExporting]);

  const numberField = (
    key: keyof typeof sliceForm,
    label: string,
    props: { min?: number; max?: number; step?: number; helperText?: string } = {}
  ): JSX.Element => {
    const { helperText, ...inputProps } = props;
    return (
      <TextField
        type="number"
        size="small"
        fullWidth
        label={label}
        value={sliceForm[key]}
        inputProps={inputProps}
        helperText={helperText}
        FormHelperTextProps={helperText ? { sx: { mx: 0 } } : undefined}
        onChange={(e) => setSliceForm((prev) => ({ ...prev, [key]: Number(e.target.value) }))}
      />
    );
  };

  return (
    <Container maxWidth="lg" sx={{ py: 4 }}>
      <Grid container justifyContent="center">
        <Grid item xs={12} md={10} lg={9}>
          <Typography variant="h5" sx={{ fontWeight: 900, textTransform: 'uppercase', mb: 1 }}>
            Gaussian Splat <Box component="span" sx={{ color: 'primary.main' }}>FAST NAV</Box>
          </Typography>
          <Typography variant="body2" color="text.secondary" sx={{ mb: 3 }}>
            Drop a <strong>.ply</strong> or <strong>.spz</strong> 3D Gaussian Splat. It renders in React Three
            Fiber, auto-runs the FAST NAV pipeline (floor field &rarr; navmesh &rarr; crowd &rarr; NPC), then frames the
            player top-down. Click the green navmesh to move the player.
          </Typography>

          <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 1, mb: 3 }}>
            {steps.map((step) => (
              <Chip
                key={step.label}
                size="small"
                color={step.done ? 'success' : step.active ? 'primary' : 'default'}
                variant={step.done || step.active ? 'filled' : 'outlined'}
                icon={
                  step.done ? (
                    <CheckCircleIcon />
                  ) : step.active ? (
                    <AutorenewIcon />
                  ) : (
                    <RadioButtonUncheckedIcon />
                  )
                }
                label={step.label}
              />
            ))}
          </Box>

          <Paper
            ref={cardRef}
            variant="outlined"
            onDragEnter={(e) => {
              e.preventDefault();
              setIsDragging(true);
            }}
            onDragOver={(e) => {
              e.preventDefault();
              setIsDragging(true);
            }}
            onDragLeave={(e) => {
              e.preventDefault();
              setIsDragging(false);
            }}
            onDrop={onDrop}
            sx={{
              position: 'relative',
              overflow: 'hidden',
              bgcolor: '#000',
              height: 'clamp(360px, 68vh, 760px)',
              outline: isDragging ? '2px dashed' : 'none',
              outlineColor: 'primary.main',
              outlineOffset: '-6px',
              '&:fullscreen': { height: '100vh', width: '100vw' },
            }}
          >
            <Box sx={{ width: '100%', height: '100%' }}>
              <SceneCanvas controller={controller} />
            </Box>

            {status === 'done' && (
              <IconButton
                onClick={toggleFullscreen}
                color="primary"
                sx={{ position: 'absolute', top: 12, right: 12, bgcolor: 'rgba(0,0,0,0.45)' }}
                title={isFullscreen ? 'Exit fullscreen' : 'Fullscreen'}
              >
                {isFullscreen ? <FullscreenExitIcon /> : <FullscreenIcon />}
              </IconButton>
            )}

            {showDropZone && (
              <Box
                sx={{
                  position: 'absolute',
                  inset: 0,
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  bgcolor: 'rgba(5,5,5,0.82)',
                  textAlign: 'center',
                  p: 4,
                }}
              >
                <Box>
                  <CloudUploadIcon sx={{ fontSize: 72, color: 'primary.main', mb: 1.5 }} />
                  <Typography variant="h6" sx={{ fontWeight: 700, mb: 1 }}>
                    Drop your splat here
                  </Typography>
                  <Typography variant="body2" color="text.secondary" sx={{ mb: 3 }}>
                    .ply or .spz · drag &amp; drop, browse, or pick an example
                  </Typography>
                  <Box sx={{ display: 'flex', flexWrap: 'wrap', justifyContent: 'center', gap: 2 }}>
                    <Button size="large" startIcon={<FolderOpenIcon />} onClick={() => fileInputRef.current?.click()}>
                      Browse files
                    </Button>
                    <Button
                      size="large"
                      color="secondary"
                      startIcon={<ViewInArIcon />}
                      endIcon={<ArrowDropDownIcon />}
                      onClick={(e) => setExampleAnchor(e.currentTarget)}
                    >
                      Example scenes
                    </Button>
                    <Menu anchorEl={exampleAnchor} open={Boolean(exampleAnchor)} onClose={() => setExampleAnchor(null)}>
                      {DEFAULT_EXAMPLE_SCENES.map((scene) => (
                        <MenuItem
                          key={scene.url}
                          onClick={() => {
                            setExampleAnchor(null);
                            void loadExample(scene.url, scene.title);
                          }}
                        >
                          {scene.title}
                        </MenuItem>
                      ))}
                    </Menu>
                  </Box>
                </Box>
              </Box>
            )}

            {isBusy && (
              <Box
                sx={{
                  position: 'absolute',
                  inset: 0,
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  bgcolor: 'rgba(5,5,5,0.6)',
                  textAlign: 'center',
                }}
              >
                <Box>
                  <CircularProgress
                    variant={!progress || progress.fraction === null ? 'indeterminate' : 'determinate'}
                    value={progress && progress.fraction !== null ? progress.fraction * 100 : undefined}
                    size={64}
                    thickness={4}
                    sx={{ mb: 1.5 }}
                  />
                  <Typography variant="body1">{statusMessage}</Typography>
                  {progressText && (
                    <Typography variant="caption" color="text.secondary">
                      {progressText}
                    </Typography>
                  )}
                </Box>
              </Box>
            )}
          </Paper>

          <Box
            sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 1, mt: 1.5 }}
          >
            <Typography variant="body2" color="text.secondary">
              {statusMessage}
            </Typography>
            {(status === 'done' || status === 'error') && (
              <Button variant="text" color="secondary" startIcon={<RefreshIcon />} onClick={reset}>
                Load another
              </Button>
            )}
          </Box>

          {status === 'done' && (
            <>
            <Accordion sx={{ mt: 2 }}>
              <AccordionSummary expandIcon={<ExpandMoreIcon />}>Navigation and collision exports</AccordionSummary>
              <AccordionDetails>
                {navSummary && (
                  <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mb: 2 }}>
                    {navSummary}
                  </Typography>
                )}
                <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 1.5, mb: 2 }}>
                  <Button startIcon={<DownloadIcon />} disabled={navExporting} onClick={() => void runNavmeshExport()}>
                    Export navmesh (.nav)
                  </Button>
                </Box>

                <Paper
                  variant="outlined"
                  sx={{
                    display: 'flex',
                    alignItems: 'center',
                    flexWrap: 'wrap',
                    gap: 2,
                    p: 1.5,
                    mb: 2,
                    background: (theme) =>
                      `linear-gradient(120deg, ${theme.palette.success.main}14, ${theme.palette.background.paper} 42%)`,
                  }}
                >
                  {navMeshVisible ? (
                    <LayersIcon color="success" />
                  ) : (
                    <LayersClearIcon color="disabled" />
                  )}
                  <Box sx={{ flexGrow: 1, minWidth: 180 }}>
                    <Typography variant="body2" fontWeight={600}>
                      Navmesh overlay
                    </Typography>
                    <Typography variant="caption" color="text.secondary">
                      {navMeshVisible
                        ? 'Green walkable mesh visible — click it to move the player'
                        : 'Hidden — click-to-move still works on the walkable surface'}
                    </Typography>
                  </Box>
                  <FormControlLabel
                    control={
                      <Switch
                        color="success"
                        checked={navMeshVisible}
                        disabled={isBusy}
                        onChange={(_, checked) => {
                          setNavMeshVisibleState(checked);
                          setNavMeshVisible(checked);
                        }}
                      />
                    }
                    label={navMeshVisible ? 'Shown' : 'Hidden'}
                  />
                </Paper>

                {collisionSummary && (
                  <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mb: 2 }}>
                    {collisionSummary}
                  </Typography>
                )}
                <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 1.5 }}>
                  <Button
                    color="secondary"
                    disabled={collisionExporting}
                    startIcon={<ViewInArIcon />}
                    onClick={() => void runCollisionGenerate()}
                  >
                    Generate collision boundary
                  </Button>
                  <Button
                    variant="outlined"
                    onClick={() => {
                      const visible = !collisionBoundaryVisible;
                      setCollisionBoundaryVisibleState(visible);
                      setCollisionBoundaryVisible(visible);
                    }}
                  >
                    {collisionBoundaryVisible ? 'Hide collision boundary' : 'Show collision boundary'}
                  </Button>
                  <Button
                    variant="outlined"
                    disabled={collisionExporting}
                    startIcon={<DownloadIcon />}
                    onClick={() => void runCollisionExport()}
                  >
                    Export collision mesh (.glb)
                  </Button>
                </Box>
              </AccordionDetails>
            </Accordion>

            <Accordion sx={{ mt: 2 }}>
              <AccordionSummary expandIcon={<ExpandMoreIcon />}>Streamed SOG export</AccordionSummary>
              <AccordionDetails>
                {sogStatusText && (
                  <Typography
                    variant="caption"
                    sx={{ display: 'block', mb: 2 }}
                    color={isLargeScene ? 'primary' : 'text.secondary'}
                  >
                    {sogStatusText}
                  </Typography>
                )}
                <ToggleButtonGroup
                  exclusive
                  size="small"
                  color="primary"
                  value={sogMode}
                  onChange={(_, value) => value && setSogMode(value as SogExportMode)}
                  sx={{ mb: 3 }}
                >
                  <ToggleButton value="streamed">Streamed LOD</ToggleButton>
                  <ToggleButton value="single">Single SOG</ToggleButton>
                </ToggleButtonGroup>

                <Grid container spacing={2}>
                  <Grid item xs={12} sm={4}>
                    {numberField('sh_degree', 'SH Degree', {
                      min: 0,
                      max: maxShDegree,
                      step: 1,
                      helperText:
                        '0 = base color only (smaller/faster). Higher degrees keep more view-dependent color.',
                    })}
                  </Grid>
                  <Grid item xs={12} sm={4}>
                    {numberField('sh_cluster_count', 'SH Palette Size', { min: 1, max: 65536, step: 256 })}
                  </Grid>
                  <Grid item xs={12} sm={4}>
                    {numberField('sh_iterations', 'SH Iterations', { min: 1, max: 50, step: 1 })}
                  </Grid>
                  {sogMode === 'streamed' && (
                    <>
                      <Grid item xs={12} sm={4}>
                        {numberField('chunk_count', 'Splats / Chunk', { min: 1000, max: 4000000, step: 16000 })}
                      </Grid>
                      <Grid item xs={12} sm={4}>
                        {numberField('chunk_extent', 'Chunk Extent (m)', { min: 0, max: maxChunkExtent, step: 1 })}
                      </Grid>
                      <Grid item xs={12} sm={4}>
                        {numberField('lod_levels', 'LOD Levels', {
                          min: 1,
                          max: 6,
                          step: 1,
                          helperText:
                            '2+ recommended for streaming (coarse base + full detail). 1 = full detail only, no multi-LOD.',
                        })}
                      </Grid>
                    </>
                  )}
                </Grid>

                {showLodLevelsWarning && (
                  <Alert severity="warning" sx={{ mt: 2 }}>
                    LOD Levels is 1 — this export is a single detail level and will not stream coarse→fine.
                  </Alert>
                )}

                <Button
                  sx={{ mt: 3 }}
                  startIcon={<DownloadIcon />}
                  disabled={sogExporting}
                  onClick={() => void runSogExport()}
                >
                  {sogExporting ? 'Exporting...' : sogExportButtonLabel}
                </Button>
              </AccordionDetails>
            </Accordion>
            </>
          )}

          {logs.length > 0 && (
            <Accordion sx={{ mt: 2 }}>
              <AccordionSummary expandIcon={<ExpandMoreIcon />}>System logs</AccordionSummary>
              <AccordionDetails>
                <Box sx={{ maxHeight: 240, overflowY: 'auto', fontFamily: 'monospace', fontSize: 12 }}>
                  {logs.map((entry) => (
                    <Box key={entry.id} sx={{ py: 0.5, display: 'flex', alignItems: 'center', gap: 1 }}>
                      <Chip
                        size="small"
                        label={entry.tag.toUpperCase()}
                        color={tagColor[entry.tag]}
                        sx={{ height: 18, '& .MuiChip-label': { px: 0.75, fontSize: 10 } }}
                      />
                      <span>{entry.message}</span>
                    </Box>
                  ))}
                </Box>
              </AccordionDetails>
            </Accordion>
          )}
        </Grid>
      </Grid>

      <input ref={fileInputRef} type="file" accept=".ply,.spz" style={{ display: 'none' }} onChange={onFileChange} />

      <Snackbar
        open={errorMessage !== null}
        autoHideDuration={6000}
        onClose={() => setErrorMessage(null)}
        anchorOrigin={{ vertical: 'bottom', horizontal: 'center' }}
      >
        <Alert severity="error" onClose={() => setErrorMessage(null)} variant="filled">
          {errorMessage}
        </Alert>
      </Snackbar>
    </Container>
  );
}
